name: Deploy backend Python ASGI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Chekcout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building docker image 
        uses: docker/build-push-action@v5
        with:
          context: ./Django_RESTful/
          file: ./Django_RESTful/Dockerfile
          push: false      
          tags: mindglitch/python-asgi:latest